spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  messages:
    basename: validation
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

logging:
  level:
    org.springframework.web: ERROR
    com.deloitte: DEBUG
